# Generated by Django 5.2.9 on 2025-12-03 15:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PayoutRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Минимальная сумма — 0.01",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Сумма выплаты",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("RUB", "Российский рубль"),
                            ("USD", "Доллар США"),
                            ("EUR", "Евро"),
                            ("KZT", "Казахский тенге"),
                        ],
                        default="RUB",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "recipient_details",
                    models.TextField(
                        help_text="Например, номер счёта, карта, электронный кошелёк",
                        verbose_name="Реквизиты получателя",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В обработке"),
                            ("approved", "Одобрена"),
                            ("rejected", "Отклонена"),
                            ("paid", "Выплачена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация (необязательно)",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на выплату",
                "verbose_name_plural": "Заявки на выплату",
                "db_table": "payout_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
